server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  profiles:
    active: prod
  config:
    import: optional:configserver:http://223.130.155.121:8888