server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    activate:
      on-profile: default

  application:
    name: api

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat-service/chats
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

        - id: post-service
          uri: lb://post-service/actuator/**
          predicates:
            - Path=/post-service/posts
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/restaurant-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}


        - id: login-route
          uri: http://localhost:8000
          predicates:
            - Path=/auth/login
          filters:
            - RemoveRequestHeader=Cookie

        - id: oauth2-route
          uri: http://localhost:8000
          predicates:
            - Path=/auth/oauth2/**
          filters:
            - RewritePath=/auth/oauth2/(?<segment>.*), /${segment}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: e2iaB9q3A_kk1k7hX6Qi
            client-secret: Av6eAE_PsV
            redirect-uri: "{baseUrl}/auth/oauth2/code/naver"
            scope: email, profile
            authorization-grant-type: authorization_code
            provider: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: "*"
    allow-credentials: true

jwt:
  secret: "bywm4zC5-vR36j_mZPsd4jmNFUuny0XuYoln59AStsI="
  expiration: 3600000  # 1시간 (밀리초 단위)

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
