spring:
  application:
    name: admin-service
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-803e8-100200353-9a8473381953.kr.lb.naverncp.com:8888/"
