spring:
  application:
    name: admin-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://223.130.155.121:8888