spring:
  application:
    name: restaurant-service
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-e74ad-100166825-82f83445b04e.kr.lb.naverncp.com:8888/"